name: Build

on:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*'

jobs:
  build_branch:
    runs-on: ubuntu-latest

    container:
      image: registry.local:5000/pipegame:latest
      options: >-
        -v ${{ gitea.workspace }}:/app

    steps:
      - uses: actions/checkout@v4

      - name: Build pipegame
        run: |
          cd game
          make all

      - name: Upload artifacts
        if: startsWith(gitea.ref, 'refs/tags/')
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: pipegame-${{ gitea.ref_name }}
          path: game/pipegame
