name: Build

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.local:5000/pipegame:latest
      options: >-
        -v ${{ gitea.workspace }}:/app

    steps:
      - uses: actions/checkout@v4

      - name: Build pipegame
        run: |
          cd game
          make all

      - name: Upload artifacts
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: pipegame
          path: game/pipegame
